### ISSUE TITLE
Hands Rotation Ain't Working

### ISSUE THREAD

**Issue by RoboEvangelist** [ros-drivers/openni_tracker#11]
Folks,

I can't get translation for the hands, but not rotation. The Rotation values remain constant per the next command:
`rosrun tf tf_echo /openni_depth_frame /left_hand_1`

And I know the frames exist, otherwise I would get errors in both ROS with the command above, or in my software...you know about those transform errors. I also checked the frames tree, and the positions are correct. 
I get something like this:

```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1466645925
        nsecs: 597857799
      frame_id: openni_depth_frame
    child_frame_id: left_hand
    transform: 
      translation: 
        x: -0.51915814209
        y: -0.575349365234
        z: 1.11227575684
      rotation: 
        x: 0.0
        y: 0.0
        z: 1.0
        w: 0.0
```

Rotation never changes. I have the same issue with the skeleton_tracker package (which also depends on the openni_tracker). Any idea what could be happening? Any yaml/xml files I could be missing? I have not modified the openni_tracker at all, though
[frames.pdf](https://github.com/ros-drivers/openni_tracker/files/329071/frames.pdf)
[right.txt](https://github.com/ros-drivers/openni_tracker/files/329070/right.txt)

.

Thanks, guys!
